INSERT INTO questions (prompt, question_type, rating) VALUES
('Have you ever pretended to like someone just to fit in?', 'TRUTH', 'PG'),
('What’s the weirdest thing you believed as a kid?', 'TRUTH', 'PG'),
('Have you ever broken something and blamed someone else?', 'TRUTH', 'PG'),
('Who do you text the most?', 'TRUTH', 'PG'),
('What’s your most irrational fear?', 'TRUTH', 'PG'),
('If you had to delete one app forever, what would it be?', 'TRUTH', 'PG'),
('Have you ever eavesdropped on someone’s conversation?', 'TRUTH', 'PG'),
('What’s the most childish thing you still do?', 'TRUTH', 'PG'),
('What’s the worst lie you’ve ever told?', 'TRUTH', 'PG'),
('Do you sing in the shower?', 'TRUTH', 'PG'),
('Have you ever had a crush on a teacher?', 'TRUTH', 'PG-13'),
('What’s your guilty pleasure song or show?', 'TRUTH', 'PG'),
('Who do you think is the best-dressed in this group?', 'TRUTH', 'PG'),
('Have you ever looked through someone’s phone without them knowing?', 'TRUTH', 'PG-13'),
('What’s the last thing you Googled?', 'TRUTH', 'PG'),
('If you could erase one memory, what would it be?', 'TRUTH', 'PG-13'),
('Who in this group would survive a zombie apocalypse the longest?', 'TRUTH', 'PG'),
('Have you ever talked about someone behind their back?', 'TRUTH', 'PG-13'),
('What’s your most embarrassing school moment?', 'TRUTH', 'PG'),
('Have you ever sent a text to the wrong person?', 'TRUTH', 'PG'),
('What’s the biggest secret you’ve kept from your parents?', 'TRUTH', 'PG-13'),
('Who do you think has the best taste in music?', 'TRUTH', 'PG'),
('Have you ever cried over a movie? Which one?', 'TRUTH', 'PG'),
("Have you ever been caught doing something you shouldn't have?", 'TRUTH', 'PG-13'),
('If you had to choose one person here to be stuck with on a deserted island, who would it be?', 'TRUTH', 'PG'),
('What’s the longest you’ve gone without showering?', 'TRUTH', 'PG'),
('Have you ever lied about your age?', 'TRUTH', 'PG-13'),
('If someone gave you $1,000 right now, what’s the first thing you’d do?', 'TRUTH', 'PG'),
('What’s something really dumb you once got in trouble for?', 'TRUTH', 'PG'),
('Do you have a secret talent you’ve never told anyone about?', 'TRUTH', 'PG'),
('Do a cartwheel or attempt one.', 'DARE', 'PG'),
('Try to touch your nose with your tongue.', 'DARE', 'PG'),
('Say the alphabet backwards in a weird accent.', 'DARE', 'PG'),
('Draw a mustache on your face with a marker.', 'DARE', 'PG'),
('Pretend to be a cat for 1 minute.', 'DARE', 'PG'),
('Do your best evil villain laugh.', 'DARE', 'PG'),
('Balance a spoon on your nose for 10 seconds.', 'DARE', 'PG'),
('Spin around 10 times and try to walk in a straight line.', 'DARE', 'PG'),
('Do an interpretive dance to no music.', 'DARE', 'PG'),
('Talk without closing your mouth until your next turn.', 'DARE', 'PG'),
('Send a funny selfie to the last person you texted.', 'DARE', 'PG'),
('Say "I love cheese" after everything you say for 3 rounds.', 'DARE', 'PG'),
('Attempt to juggle three random objects.', 'DARE', 'PG'),
('Try to impersonate someone in the group.', 'DARE', 'PG'),
('Text your crush a single period.', 'DARE', 'PG-13'),
('Call someone and sing “Happy Birthday” to them.', 'DARE', 'PG'),
('Let someone redo your hair.', 'DARE', 'PG'),
('Pretend your hand is a phone and have a fake conversation.', 'DARE', 'PG'),
('Send “I have a confession…” to a random person.', 'DARE', 'PG-13'),
('Wear socks on your hands for the next 3 rounds.', 'DARE', 'PG'),
('Use a random object as a microphone and sing for 30 seconds.', 'DARE', 'PG'),
('Let someone write a word on your forehead with a washable marker.', 'DARE', 'PG'),
('Take a silly photo and post it to your story.', 'DARE', 'PG-13'),
('Speak in only emoji (out loud) for 1 minute.', 'DARE', 'PG'),
('Try to lick your elbow and don’t stop until someone tells you to.', 'DARE', 'PG'),
('Let the group go through your recent emojis.', 'DARE', 'PG-13'),
('Send “Can I borrow $100?” to someone random.', 'DARE', 'PG-13'),
('Make a dramatic scene like you’re in a soap opera.', 'DARE', 'PG'),
('Let someone else send a text using your phone.', 'DARE', 'PG-13'),
('Do the Macarena silently until someone notices.', 'DARE', 'PG');

